apiVersion: 1
datasources:
  - name: ODS Postgres
    type: postgres
    url: postgres:5432
    database: ods_dev
    user: ods
    secureJsonData:
      password: ods
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
    editable: true
